### ISSUE TITLE
Cannot generate DTOs from inner classes.

### ISSUE THREAD

**Issue by PixelBumper** [inspire-software/geda-genericdto#4]
I have an entity class with a field that uses public inner class and I unfortunately cannot assemble the dto when trying to get values from it.
Example:
```java
class Entity{
	private InnerClass inner;
	// getter /setter

	public static class InnerClass{
		private String value;
		// getter/setter
	}
}

@Dto
class Dto(){

	@DtoValue("inner.value")
	private String value;
	//getter setter
}
//...
final Entity entity = new Entity();
final Dto dto = new Dto();
DTOAssembler.newAssembler(Dto.class, Entity.class).assembleDto(dto, entity, null, null);
//...

```
```
GeDARuntimeException: Unable to identify interface for proxy object
  at com.inspiresoftware.lib.dto.geda.assembler.extension.impl.AbstractMethodSynthesizer.getValidDeclaringClass(AbstractMethodSynthesizer.java:85)
  at com.inspiresoftware.lib.dto.geda.assembler.extension.impl.AbstractMethodSynthesizer.preMakeReaderValidation(AbstractMethodSynthesizer.java:233)
  at com.inspiresoftware.lib.dto.geda.assembler.extension.impl.AbstractMethodSynthesizer.synthesizeReader(AbstractMethodSynthesizer.java:321)
  at com.inspiresoftware.lib.dto.geda.assembler.MethodSynthesizerProxy.synthesizeReader(MethodSynthesizerProxy.java:185)
  at com.inspiresoftware.lib.dto.geda.assembler.DataPipeBuilder.build(DataPipeBuilder.java:104)
  at com.inspiresoftware.lib.dto.geda.assembler.DataPipeBuilder.build(DataPipeBuilder.java:33)
  at com.inspiresoftware.lib.dto.geda.assembler.DTOtoEntityAssemblerImpl.createPipeChain(DTOtoEntityAssemblerImpl.java:175)
  at com.inspiresoftware.lib.dto.geda.assembler.DTOtoEntityAssemblerImpl.createPipeChain(DTOtoEntityAssemblerImpl.java:199)
  at com.inspiresoftware.lib.dto.geda.assembler.DTOtoEntityAssemblerImpl.mapRelationMapping(DTOtoEntityAssemblerImpl.java:137)
  at com.inspiresoftware.lib.dto.geda.assembler.DTOtoEntityAssemblerImpl.<init>(DTOtoEntityAssemblerImpl.java:99)
  at com.inspiresoftware.lib.dto.geda.assembler.DTOtoEntityAssemblerImpl.<init>(DTOtoEntityAssemblerImpl.java:71)
  at com.inspiresoftware.lib.dto.geda.assembler.DTOAssembler.createNewAssembler(DTOAssembler.java:146)
  at com.inspiresoftware.lib.dto.geda.assembler.DTOAssembler.newAssembler(DTOAssembler.java:532)
  at com.inspiresoftware.lib.dto.geda.assembler.DTOAssembler.newAssembler(DTOAssembler.java:491)
```

PS I think this relates to this one too
http://www.inspire-software.com/jira/browse/GEDA-61

**Comment by denyspavlov** [comment]
Hi,

Yes it is a know issue. 

It has not been addresses as the workaround is quite simple - move the inner class to be "normal" class.

The rationale for not implementing the "Inner" classes is that in terms of GeDA philosophy it is a bad practice. If you allow information from your entities to be freely copied using such tools as GeDA then each piece of information has to be autonomous and public and hence defined in it own separate class. 

Usually there is no need to have inner classes to describe the domain model. If there are complex domain models that use inner classes to remove some of the complexity via encapsulation then you may also consider @VirtualField annotation and then use value converter to perform any custom logic necessary.

Hope this helps.

P.S. There is always a trade off between amount of features supported, speed of execution and security concerns. This particular issue is one of these trade offs.
